name: Deployment Workflow
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Run deploy script now
      uses: appleboy/ssh-action@master
      with: 
        host: '18.134.46.14'
        username: bitnami
        key: ${{ secrets.AWSLIGHTSAIL_SSH_KEY }}
        port: 22
        script: |
          cd ~/matched-bet-scanner-frontend
          git pull origin main
          npm run build
          cp -a build/. /home/bitnami/htdocs/
